# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bepro-ios-task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bepro-ios-task
    pod 'RxSwift', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'
    pod 'RxSwiftExt', '~> 5.1'
    pod 'RxDataSources', '~> 4.0'
    pod 'Alamofire', '~> 4.7'
    pod "AlamofireObjectMapper", "~> 5.2"

  target 'bepro-ios-taskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bepro-ios-taskUITests' do
    # Pods for testing
  end

end
